<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript">
    function addItem()
    {     
        var text=document.getElementById("element_8").value;
        var opt = document.createElement("option");      
        opt.text = text;
        opt.value = text;
        opt.selected="selected";
        document.getElementById("element_1").options.add(opt);
               
    }
</script>

</head>
<body id="main_body" >

<?php 
include("ListFunction.php");
//echo("ohé");

if (isset($_POST["target"])){
//echo($_POST["type"]);
}
$name='answer';


	

	//print_r($previouslist);
	
	//$infos['properties']=$TabProperties;
	
	
	$options=loadList("property",$name);
	
	$p2='" >';
	$p3='</option>';

?>


	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Untitled Form</a></h1>
		<form id="form_470585" class="appnitro"  method="post" action="<?php if (isset($_POST["sender"])){echo($_POST["sender"]); }?>">
					<div class="form_description">
			<h2>Modifications des propriétés</h2>
			
				<?php if (isset($_POST["target"])){
					echo(base64_decode($_POST["target"]));
					 }?>
				
				<h3>Cliquez sur les propriétés désirées</h3>
			
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Propriétés </label>
		<div>
		<select class="element select large" id="element_1" name="properties[]" multiple="multiple" size="25">
		<?php foreach($options as $option){
			$p1='<option value="';	
			echo($p1.$option.$p2.$option.$p3); //<option value="First option" >First option</option> etc...
			//selected="selected"
		}
			
			?>
		</select>
		</div><p class="guidelines" id="guide_1"><small>Ctrl+click pour choisir plusieurs propriétés.</small></p> 
		</li>
		<li>	
		<label class="description" >Ajoutez une propriété à la liste</label>
		<input id="element_8" name="element_8" class="element text medium" type="text" maxlength="255" value=""/> 
		<input id="saveForm" class="button_text" type="button" name="ajout" value="ajout"  onclick="addItem();" />
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="470585" />
				<input id="saveForm" class="button_text" type="submit" name="submit" value="OK" />
		</li>
			</ul>
		</form>	
		
	<?php require_once("conn.php");$sql = "SELECT * FROM pbm_globalcontent ";

  $result = mysql_query($sql) or die ("Requête incorrecte");
  // = mysql_numrows($query);
  if ($result) { // Si il y'a des résultats
 // while ($rs = mysql_fetch_array($query)) {
 $t=0;
  while ($enregistrement = mysql_fetch_assoc($result))
		{
		  $text1 =  $enregistrement["Text_html"];
		  $id= $enregistrement["id"];
?>
	<div style="width:350px;display:inline-block;margin:0 0 5px 40px;padding:10px;border:1px solid black"> 
	  <?php echo( $text1); ?>
	 </div> <?php } }?>
	 <div style="width:70px;display:inline-block;margin:0 0 5px 40px">
	 <input type="button" value="copier ce modèle" id="Quest" onClick="parent.location='openPbm.php?id=<?php echo($id);?>'"/>
	 </div></li>

		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
	
</html>